### ISSUE TITLE
是否可以绑定多个哔哩哔哩ID？

### ISSUE THREAD

**Issue by phoenix5980** [UnluckyNinja/worker-bilibili-discord#1]
`user.config.ts`中`bilibili_id:`后面貌似不是一个array，是只能对应一个哔哩哔哩ID么？如果要转发多个B站动态内容需要怎样配置

**Comment by UnluckyNinja** [comment]
目前`onSchedule`是针对单独帐号的完整逻辑，帐号是写在函数这个位置的 https://github.com/UnluckyNinja/worker-bilibili-discord/blob/911c3f74dbd8b428f25b1133c584f5650aa76388/src/triggers.ts#L48  
可以逐级往外抽取成参数，再把`onSchedule`方法提取出单独逻辑，并改为用帐号数组对单独逻辑进行循环调用应该就行了
这两天有空时我试试改一下

**Comment by UnluckyNinja** [comment]
已更新，user.config.ts已改成可以设置多个订阅用户的形式，但可能需要更多测试

**Comment by phoenix5980** [comment]
> 已更新，user.config.ts已改成可以设置多个订阅用户的形式，但可能需要更多测试

`wrangler 2.1.13
--------------------
✘ [ERROR] Could not resolve "itty-router"

    src/index.ts:13:23:
      13 │ import { Router } from 'itty-router';
         ╵                        ~~~~~~~~~~~~~

  You can mark the path "itty-router" as external to exclude it from the bundle, which will remove
  this error.


✘ [ERROR] Build failed with 1 error:

  src/index.ts:13:23: ERROR: Could not resolve "itty-router"
`
